model_name: "Qwen/Qwen2.5-0.5B"
data_path: "../processed_dataset/ultrafeedback_binarized_train_prefs_small.json"
batch_size: 4
max_length: 1024
learning_rate: 0.0000001
num_epochs: 1
gradient_accumulation_steps: 8
log_steps: 100
save_steps: 10000
eval_method: "reward_function"
reward_model_name: "Qwen/Qwen2.5-0.5B"
reward_model_weights_path: "reward_model.pt"
task: "ultrafeedback"
k: 4