_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 2
beta:
    value: 0.5
data_path:
    value: ../processed_dataset/ultrafeedback_binarized_train_prefs_small.json
learning_rate:
    value: "1e-6"
max_length:
    value: 512
model_name:
    value: Qwen/Qwen2.5-0.5B
num_epochs:
    value: 10
