model_name: "./ckpts_old/dpo_last_continue"
data_path: "../processed_dataset/ultrafeedback_binarized_train_prefs_better2.json"
batch_size: 4
max_length: 1280
learning_rate: 0.000001
num_epochs: 3
beta: 0.1
log_steps: 10
save_steps: 2000
gradient_accumulation_steps: 16
deepspeed_config: "./config/ds_z1_config.json"
