model_name: "Qwen/Qwen2.5-0.5B"
data_path_list: ["../processed_dataset/processed_warm_start_dataset_extension_128_512_train.json"]
batch_size: 4
max_length: 1280
learning_rate: 0.00002
num_epochs: 50
log_steps: 10
save_steps: 1000
gradient_accumulation_steps: 16
save_dir: "sft_warm_extension"