model_name: "./models/sft_smol_with_system"
data_path_list: ["../processed_dataset/processed_smol_talk_dataset_128_512_train_filtered.json"]
batch_size: 4
max_length: 1280
learning_rate: 0.00002
num_epochs: 3
log_steps: 10
save_steps: 40000
gradient_accumulation_steps: 16
save_dir: "sft_smol_with_system"
