model_name: "/viscam/u/tonyzst/Research/test/SFT/models/base_model"
data_path_list: ["/viscam/u/tonyzst/Research/test/processed_dataset/processed_warm_start_dataset_128_512_train.json"]
batch_size: 4
max_length: 1280
learning_rate: 0.00001
num_epochs: 20
log_steps: 10
save_steps: 1000
gradient_accumulation_steps: 16
save_dir: "sft_warm"