model_name: "Qwen/Qwen2.5-0.5B"
data_path_list: ["../processed_dataset/processed_smol_talk_dataset.json", "../processed_dataset/processed_warm_start_dataset.json"]
batch_size: 1
max_length: 1024
learning_rate: 0.00001
num_epochs: 3
