model_name: "/viscam/u/tonyzst/Research/test/SFT/models/base_model"
data_path_list: ["/viscam/u/tonyzst/Research/test/processed_dataset/processed_smol_talk_dataset_128_512_train.json"]
batch_size: 4
max_length: 1024
learning_rate: 0.00002
num_epochs: 1
gradient_accumulation_steps: 8
log_steps: 100
warm_up_steps: 200
save_steps: 10000
save_dir: "/home/ubuntu/CS224R-Project/ckp/qwen_sft"
